project_name: octopus

release:
  prerelease: auto
  draft: true # we publish during the Octopus deployment
  name_template: "Octopus CLI {{.Version}}"

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "octopus"
    main: ./cmd/octopus
    binary: "{{ .ProjectName }}"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: linux-distributions
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    formats:
      rpm
      deb

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: all
    args:
      [
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
    stdin: "{{ .Env.GPG_PASSWORD }}"

changelog:
  skip: true
