version: 2

project_name: octopus

release:
  prerelease: auto
  name_template: "Octopus CLI {{.Version}}"

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "octopus"
    main: ./cmd/octopus
    binary: "{{ .ProjectName }}"

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- if eq .Os \"darwin\"}}macOS{{- else }}{{ .Os }}{{ end }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

nfpms:
  - license: Apache 2.0
    maintainer: Octopus Deploy
    package_name: octopus-cli
    homepage: https://github.com/OctopusDeploy/cli
    bindir: /usr/bin
    description: Octopus Deploy's official command line tool.
    formats:
      - rpm
      - deb
    rpm:
      signature:
        key_file: "{{ .Env.GPG_PRIVATE_KEY_FILE }}"
    deb:
      signature:
        key_file: "{{ .Env.GPG_PRIVATE_KEY_FILE }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: all
    args:
      [
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
    stdin: "{{ .Env.GPG_PASSWORD }}"

changelog:
  skip: true

brews:
  - name: "octopus-cli"

    tap:
      owner: OctopusDeploy
      name: homebrew-taps

    homepage: "https://github.com/OctopusDeploy/cli"
    description: "The New CLI (octopus) for Octopus Deploy, a user-friendly DevOps tool for developers that supports release management, deployment automation, and operations runbooks"
    license: "Apache-2.0"

    skip_upload: true

    test: |
      system "#{bin}/octopus", "--help"

    install: |
      bin.install "octopus"
      # future: enhance the CLI to generate completion scripts, and install them as follows
      # bash_completion.install "completions/octopus.bash" => "octopus"
      # zsh_completion.install "completions/octopus.zsh" => "_octopus"
      # fish_completion.install "completions/octopus.fish"
