on:
  push:
    branches:
      - release-please--**
name: "Update Install Script Version"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.INTEGRATIONS_FNM_BOT_TOKEN }}
      - name: Update Install Script
        run: |-
          NEW_VERSION="v$(cat version.txt)"
          sed -i "s/\(VERSION:-\)v[0-9]*\.[0-9]*\.[0-9]*/\1${NEW_VERSION}/g" scripts/install.sh
      - name: Commit
        run: |-
          git config --global user.name "team-integrations-fnm-bot"
          git config user.email 'integrationsfnmbot@octopus.com'
          git add scripts/install.sh
          git diff-index --quiet HEAD || (git commit -m "chore: update install script version" && git push origin)

