name: 'Generate Docs'
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  generate-docs:
    runs-on: ubuntu-18.04
    steps:
      - name: Calculate branch name
        id: branch-name
        run: echo "BRANCH_NAME=enh-cliupdate-octopus-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Checkout CLI
        uses: actions/checkout@v3
        with:
          path: cli

      - name: Checkout docs
        uses: actions/checkout@v3
        with:
          repository: benPearce1/docs
          path: docs
          token: ${{ env.GH_TOKEN }}
          username: benPearce1
          persist-credentials: true

      - name: Setup docs repo
        working-directory: docs
        run: |
          git config user.email 'benpearce@yahoo.com'
          git config user.name benPearce1
          git checkout master
          git checkout -b $BRANCH_NAME
          git status

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

#      - name: Create branch
#        uses: peterjgrainger/action-create-branch@v2.2.0
#        working-dir: docs
#        env:
#          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
#        with:
#          branch: ${{ env.BRANCH_NAME }}

      - name: Generate cli docs
        working-directory: cli
        run: go run cmd/gen-docs/main.go --website --doc-path ../docs/docs/octopus-rest-api/cli

#      - name: Update docs
#        #working-directory: docs
#        run: |
#          echo "# configuring git"
#          pushd docs
#          git config user.email 'benpearce@yahoo.com'
#          git config user.name benPearce1
#          git checkout -b $BRANCH_NAME
#          git status
#          popd
#
#          echo "# generating docs"
#          pushd cli
#          go run cmd/gen-docs/main.go --website --doc-path ../docs/docs/octopus-rest-api/cli
#          popd
#
#          echo "# adding files"
#          pushd docs
#          pwd
#          ls -lah
#          git add --verbose .
#          git status
#
#          echo "# committing"
#          git commit --verbose -m 'Update cli docs for octopus(go)'
#          git log
#          git status
#
#          echo "# pushing"
#          git push --repo https://${GITHUB_TOKEN}@github.com/benPearce1/docs.git --set-upstream origin $BRANCH_NAME
#          git status
#
#          echo "# creating pr"
#          gh auth token $GH_TOKEN
#          gh pr create --repo benPearce1/docs --base $BRANCH_NAME --fill
#          popd
#
#

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update cli docs for octopus(go)'
          author_name: Ben Pearce
          author_email: benpearce@yahoo.com
          committer_name: benPearce1
          cwd: docs
          add: docs/octopus-rest-api/cli

      - run: git push --set-upstream origin $BRANCH_NAME
        working-directory: docs

      - name: Create PR
        working-directory: docs
        run: |
          gh auth token $GH_TOKEN
          gh pr create --repo benPearce1/docs --base $BRANCH_NAME --fill
          
          
