on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          token: ${{ secrets.INTEGRATIONS_FNM_BOT_TOKEN }}
          command: github-release
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-go@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          go-version: 1.18
      - name: goreleaser
        if: ${{ steps.release.outputs.release_created }}
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
  release-please-pr:
    runs-on: ubuntu-latest
    needs:
      - release-please-release
    steps:
      - id: release-pr
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.INTEGRATIONS_FNM_BOT_TOKEN }}
          release-type: go
          command: release-pr